### ISSUE TITLE
When using path fill, the CVS grows exponentially.

### ISSUE THREAD

**Issue by songhuaixu** [audulus/vger-rs#22]
When using path fill, the CVS grows exponentially.

**Comment by songhuaixu** [comment]
> @songhuaixu Can you provide some code to repro?

![test](https://github.com/user-attachments/assets/0eea0315-5f78-4ffa-940b-958ec128954a)

This SVG file contains 606 points but generated 101883 cvs using PathScanner

**Comment by wtholliday** [comment]
@songhuaixu please write a test which reproduces this issue. I would put the 909 points in an array and show what `PathScanner` does.

**Comment by songhuaixu** [comment]
[tests.rs.zip](https://github.com/user-attachments/files/17607774/tests.rs.zip)
@wtholliday this is test codes.

**Comment by wtholliday** [comment]
I suspect it's quadratic, not exponential.

`PathScanner` is meant for relatively simple paths, like the ones I use for UI in my apps. vger would need a more sophisticated algorithm for handling paths where a horizontal scan line can intersect many path segments. In your case, many of the scan lines intersect > 100 path segments. That's kind of a pathological path to throw at poor `PathScanner`.

I'm not interested in working on a more sophisticated algorithm, sorry. I'd recommend you check out a more sophisticated renderer such as [Vello](https://github.com/linebender/vello)

**Comment by songhuaixu** [comment]
Well, thank you
